### ISSUE TITLE
Feature: User can enter zip code to find the weather

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/star-gazer#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can enter the zipcode of their choice to get the weather
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Can enter the zip code of choice in order to see if tonight will be a good night to go stargazing 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/78828085/114478544-7a27e280-9bcc-11eb-81ee-35c315935507.png)
![Screen Shot 2021-04-12 at 8 20 54 PM](https://user-images.githubusercontent.com/78828085/114478642-b9563380-9bcc-11eb-934f-7d6267a194a4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a header that has area for a title and icon with moon and clouds
- [x]  create a footer that has three icons: Moon and cloud book and star
- [x]  create three cards for the API data to be appended to the html 
- [x] create input for zip code to be entered 
- [x] set data-view to be weather
- [x] listen for target value of zip code input field
- [x] set up event listener for icon in header 
- [x] create data set for api information
- [x] setup local storage for the api information to be gathered
- [x] Change the input to have a red border and red text when an invalid zip code has been entered
- [x]  Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] add spinning moon when loading
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
