### ISSUE TITLE
Feature: User can enter observations

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/star-gazer#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can enter their observations into record keeper

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Can enter information and store it to keep a record of all of the stargazing adventures

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-04-12 at 8 38 11 PM](https://user-images.githubusercontent.com/78828085/114479730-17841600-9bcf-11eb-9562-9cbc40ecb8df.png)
![Screen Shot 2021-04-12 at 8 38 25 PM](https://user-images.githubusercontent.com/78828085/114479751-1fdc5100-9bcf-11eb-8093-156998be8929.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add data-view "observation" to observations
- [x] create layout for the observations area.  Look at wireframe. 
- [x]  Create event listener for book button that will view-swap between weather view and observation view 
- [x] Create form for observations
- [x] All inputs in form should be required 
- [x] Have the zip input connected to api so that the other input can be "auto" rendered.
- [x] The picture should be auto rendered as well with the current days photo of the day from the NASA API
- [x]  Create a request for the NASA API and have it connected to the Astronomy API to grab the day
- [x] Location is there for flexibility but will be auto generated as well.
- [x] After new entry the form returns to being blank 
- [x] Create a record button that is used to record the data.
- [x] Make sure the data is being saved in the observationsData object 
- [x] check and see if the observationsID is being incremented by 1 every time there is an observation.
- [x] Check to see if toggle works correctly. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by jdfenlason** [comment]
<img width="479" alt="Screen Shot 2021-04-15 at 4 13 01 PM" src="https://user-images.githubusercontent.com/78828085/114932436-81860080-9e05-11eb-8b4d-230d58612afd.png">
<img width="479" alt="Screen Shot 2021-04-15 at 4 13 10 PM" src="https://user-images.githubusercontent.com/78828085/114932446-83e85a80-9e05-11eb-8875-53bb03daf89a.png">
<img width="1669" alt="Screen Shot 2021-04-15 at 4 02 59 PM" src="https://user-images.githubusercontent.com/78828085/114932481-8f3b8600-9e05-11eb-9c0f-64ed93fb1613.png">
<img width="1651" alt="Screen Shot 2021-04-15 at 4 02 26 PM" src="https://user-images.githubusercontent.com/78828085/114932515-96fb2a80-9e05-11eb-9a56-71e99865005a.png">
![Screen Shot 2021-04-15 at 4 11 17 PM](https://user-images.githubusercontent.com/78828085/114932564-a4b0b000-9e05-11eb-9575-70a18d279fb1.png)
