### ISSUE TITLE
Feature: User can edit and delete past observations

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/star-gazer#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit and delete past observations

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Can look back at old entries and update any information that was misinterpreted
 or delete observations all together.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2021-04-12 at 8 42 46 PM](https://user-images.githubusercontent.com/78828085/114480034-ae50d280-9bcf-11eb-9c54-7cee10c9fc76.png)
![Screen Shot 2021-04-12 at 8 44 20 PM](https://user-images.githubusercontent.com/78828085/114480131-e6f0ac00-9bcf-11eb-9eaa-e51e43ac7eac.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add new button at top of page above observations
- [x] Add event listener to new button 
- [x] Attach new button to book icon to change the dataview to observations
- [x] Create function to render data to the page. 
- [x] Append an edit icon in the upper right hand corner of the list
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Picture goes on front of the card and the back of the card has the observation from the night
- [x] Date location and zip code get put onto the page in a list form 
- [x] Create a function that opens to the edit page when the edit icon is pushed
- [x] Make sure the corresponding observation is there to be edited
- [x] Create a delete button that makes the modal appear when the button is pushed
- [x] Create overlay 
- [x] Modal is to go on top of page cancel takes back to edit form cancel deletes observations and goes back to the observations view
- [x] make sure newest observation is seen first.
- [x] make sure that observations are being deleted 
- [x] make sure that observations are being edited. 
- [x] stay stress-free 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
