### ISSUE TITLE
Feature: User can search old observations

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/star-gazer#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search through old observations 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Can search through observations using a search bar 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2021-04-12 at 8 46 29 PM](https://user-images.githubusercontent.com/78828085/114480242-31722880-9bd0-11eb-8837-573fe26f0db6.png)
![Screen Shot 2021-04-12 at 8 47 19 PM](https://user-images.githubusercontent.com/78828085/114480285-4bac0680-9bd0-11eb-80b0-27f27b6f211d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can search old observations 
- [x] create search bar for the past observations 
- [x] listen for search input 
- [x] create function for the search 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
