### ISSUE TITLE
Feature: User can pick favorite observations

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/star-gazer#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose 5 favorite observations 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Can pick 5 favorite observations that will be displayed in a slideshow in a favorite tab section 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2021-04-12 at 8 50 31 PM](https://user-images.githubusercontent.com/78828085/114480569-c70db800-9bd0-11eb-8144-3f1b03f97fe2.png)
![Screen Shot 2021-04-12 at 8 49 59 PM](https://user-images.githubusercontent.com/78828085/114480566-c412c780-9bd0-11eb-9bcb-5c3befe42221.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Put a button on each ul entry dynamically in the DOM
- [x] create icons for favorite page
- [x] listen to star icon at bottom of page
- [x] change display to  favorites page
- [x]  Put the Icon at the  star at the bottom, of the picture 
- [x] Make the picture relative and the star absolute 
- [x] Two stars one that is solid and one that is empty 
- [x] Listen for the two stars 
- [x] Create a function that pushes the star into new array []
- [x] event into an array called favorites that pushes the picture image value
- [x] Render that array in  new data-view favorites from the Dom 
- [x] create a function that carousels the dom elements every 5 seconds.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
